Repository Everest-Option-Exchange-Team/contracts, pull requests merged in 2022-04, with the labels that each got.

#1 Set up CI workflow
  .github/workflows/main.yml
Labels: enhancement

#3 Added new field to obtain total funds
  contracts/Fund.sol
Labels: help wanted, question

#5 Added getAddressToAmountFunded()
  contracts/Fund.sol
Labels: enhancement, ready

#4 run.js init
  hardhat.config.js
  scripts/deploy.js
  scripts/run.js
Labels: enhancement, approvers needed

#8 Write tests
  .env.sample
  README.md
  contracts/Fund.sol
  hardhat.config.js
  package-lock.json
  package.json
  test/fund.js
Labels: enhancement

#10 Withdraw custom amount from the fund
  contracts/Fund.sol
  test/fund.js
Labels: enhancement, approvers needed

#11 Format code and update getAddressToAmountFunded() documentation
  contracts/Fund.sol
Labels: documentation, approvers needed

#15 Add latest deployment table in README.md
  README.md
Labels: enhancement

#13 Analyse Solidity code with Slither and Mythril
  .github/workflows/main.yml
  contracts/Fund.sol
Labels: enhancement

#18 Fix gas estimation
  hardhat.config.js
Labels: enhancement

#20 Add Deposit and Withdraw events
  contracts/Fund.sol
Labels: enhancement

#25 Deploy contract on fuji testnet
  README.md
Labels: enhancement

#24 in package.json scripts modified
  README.md
  package.json
  scripts/run.js
Labels: enhancement

#28 Add fuji faucet links
  README.md
Labels: documentation
